In [1]:
import numpy as np
import pandas as pd

In [2]:
# Loading the training data from the PC.
data = pd.read_csv(r"C:\Users\tushant\Desktop\ML\NLP\Project_twitter\train_data.csv")

In [3]:
data.keys()

Index(['tweet_id', 'airline_sentiment', 'airline', 'airline_sentiment_gold',
       'name', 'negativereason_gold', 'retweet_count', 'text', 'tweet_coord',
       'tweet_created', 'tweet_location', 'user_timezone'],
      dtype='object')

In [4]:
x = data.text
y = data.airline_sentiment

In [5]:
# Making numpy array of x and y
x = x.values
y = y.values
print(x.shape)
print(y.shape)


(10980,)
(10980,)


In [6]:
# Making the y array label 
# 0 for neutral
# 1 for positive
# 2 for neutral
y_train = []
for value in y:
    if value == "positive":
        y_train.append(1)
    elif value == "neutral":
        y_train.append(0)
    else:
        y_train.append(2)
y_train = np.array(y_train)

In [7]:
print(y_train[0:10])
x[0]

[2 1 1 2 2 2 2 1 2 1]


'@SouthwestAir I am scheduled for the morning, 2 days after the fact, yes..not sure why my evening flight was the only one Cancelled Flightled'

In [8]:
# Cleaning the training data
from nltk.corpus import stopwords
import string 
stop = stopwords.words("english")
punctuation = list(string.punctuation)
stop += punctuation


In [9]:
# from nltk.stem import WordNetLemmatizer
# lemmatizer = WordNetLemmatizer()
def clean_words(words):
    output_words = []
    words = words.split(" ") #Making the seperate words
    for word in words:
        if word.lower() not in stop:
            output_words.append(word)
    return output_words

In [10]:
x_clean = [clean_words(a) for a in x]

In [11]:
x_train = [" ".join(a) for a in x_clean]
x_train[0]

'@SouthwestAir scheduled morning, 2 days fact, yes..not sure evening flight one Cancelled Flightled'

In [12]:
# from sklearn.model_selection import train_test_split
# x_train, x_test, y_train, y_test = train_test_split(x_string, y_train)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
count_vec = CountVectorizer(max_features = 100,ngram_range=(1, 2))
x_t = count_vec.fit_transform(x_train)
x_t.todense()

matrix([[0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
print(count_vec.get_feature_names())

['agent', 'airline', 'airport', 'americanair', 'amp', 'another', 'back', 'bag', 'bags', 'call', 'can', 'cancelled', 'cancelled flightled', 'change', 'check', 'co', 'could', 'customer', 'customer service', 'day', 'delay', 'delayed', 'dm', 'even', 'first', 'flight', 'flightled', 'flights', 'fly', 'flying', 'gate', 'get', 'getting', 'go', 'going', 'good', 'got', 'great', 'guys', 'help', 'hold', 'home', 'hour', 'hours', 'http', 'http co', 'it', 'jetblue', 'know', 'last', 'late', 'like', 'lost', 'love', 'luggage', 'make', 'me', 'minutes', 'much', 'need', 'never', 'new', 'now', 'one', 'people', 'phone', 'plane', 'please', 'really', 'seat', 'see', 'service', 'southwestair', 'still', 'take', 'thank', 'thank you', 'thanks', 'that', 'ticket', 'time', 'today', 'told', 'tomorrow', 'trying', 'united', 'us', 'usairways', 've', 'virginamerica', 'wait', 'waiting', 'want', 'way', 'we', 'weather', 'worst', 'would', 'yes', 'you']


In [16]:
from sklearn.svm import SVC

In [17]:
# # Chossing the best parameters
# from sklearn.model_selection import GridSearchCV
# clf = SVC()
# grid = {'C' : [1e2, 1e3, 5e3, 1e4, 5e4, 1e5],
#        'gamma' : [1e-3, 5e-4, 1e-4, 5e-3]}
# abc = GridSearchCV(clf, grid)
# abc.fit(x_t, y_train)

In [18]:
# abc.best_estimator_

In [19]:
svc = SVC(C=50000.0, gamma=0.0005)

In [20]:
# x_test_t = count_vec.transform(x_test)
# y_pred = svc.predict(x_test_t)
# y_pred
# svc.score(x_test_t, y_test)

In [21]:
# testing data
testing = pd.read_csv(r"C:\Users\tushant\Desktop\ML\NLP\Project_twitter\test_twitter_x_test.csv")

In [22]:
testing.keys()

Index(['tweet_id', 'airline', 'airline_sentiment_gold', 'name',
       'negativereason_gold', 'retweet_count', 'text', 'tweet_coord',
       'tweet_created', 'tweet_location', 'user_timezone'],
      dtype='object')

In [23]:
testing_data = testing.text
print(type(testing_data))
testing_data = testing_data.values
print(type(testing_data))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [24]:
x_clean_test = [clean_words(a) for a in testing_data]
x_string_test = [" ".join(a) for a in x_clean_test]
x_string_test[0]

"@AmericanAir car gng DFW. Pulled 1hr ago icy roads. On-hold AA since 1hr. Can't reach arpt AA2450. Wat 2 do?"

In [25]:
x_test = count_vec.transform(x_string_test)
x_test.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
svc.fit(x_t, y_train)
y_pred = svc.predict(x_test)


In [27]:
y_s = []
for value in y_pred:
    if value == 1:
        y_s.append("positive")
    elif value == 0:
        y_s.append("neutral")
    else:
        y_s.append("negative")
y_s = np.array(y_s)

In [28]:
np.savetxt("test.csv",y_s,fmt='%s')

In [31]:
y_s.shape

(3660,)

In [33]:
s = ["Very Good Service"]
s_clean_test = [clean_words(a) for a in s]
s_string_test = [" ".join(a) for a in s_clean_test]
s_test = count_vec.transform(s_string_test)

s_pred = svc.predict(s_test)

In [34]:
s_pred

array([2])