In [1]:
import numpy as np

In [2]:
# We are going to work with the AND gate here.
# Also we are going to work with a basic neural network with no hidden layer and only the output layer.
X = np.array([[0,0],[1,0],[0,1],[1,1]])
Y = np.array([0,0,0,1]).reshape(-1,1)
print(X.shape)
print(Y.shape)

(4, 2)
(4, 1)


In [6]:
# Defining the sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [29]:
# We are randomly picking the weights between -1 to 1.
weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random((1)) - 1
weights, bias

(array([[-0.4277969 ],
        [-0.08952903]]), array([0.72223415]))

In [31]:
# Forward propagation for the no hidden layer network.
output0 = X
output = sigmoid(np.dot(output0,weights) + bias)
output

array([[0.6730988 ],
       [0.5730821 ],
       [0.65310259],
       [0.55104856]])

In [32]:
# Picking weihgt for the one hidden layer network.
weight_h =  2*np.random.random((2,2)) - 1
weight_output =  2*np.random.random((2,1)) - 1
bias_h =  2*np.random.random((1,2)) - 1
bias_output =  2*np.random.random((1)) - 1

In [36]:
# Forward propagation for the one hidden layer network.
output1 = sigmoid(np.dot(X,weight_h) + bias_h) # Output at layer 1
output = sigmoid(np.dot(output1,weight_output) + bias_output)
output

array([[0.51993161],
       [0.5401271 ],
       [0.5321031 ],
       [0.54923395]])

## We are going to write the derivative of sigmiod funcion. If 'y' is sigmoid function than the value of it's derivative is y(1-y).

In [37]:
# Derivative of sigmoid
def derivativeSig(z):
    return sigmoid(z)(1 - sigmoid(z))