## We are going to implement a neural network with no hidden layer.

In [2]:
import numpy as np

In [3]:
# We are going to work with the AND gate here.
# Also we are going to work with a basic neural network with no hidden layer and only the output layer.
X = np.array([[0,0],[1,0],[0,1],[1,1]])
Y = np.array([0,0,0,1]).reshape(-1,1)
print(X.shape)
print(Y.shape)

(4, 2)
(4, 1)


In [4]:
# Defining the sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
# Derivative of sigmoid
def derivativeSig(z):
    return sigmoid(z)(1 - sigmoid(z))

In [64]:
# We are randomly picking the weights between -1 to 1.
weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random((1)) - 1
# Learning Rate
lr = 0.1
weights, bias

(array([[-0.8070052],
        [ 0.6489754]]), array([-0.87444354]))

In [70]:
# Forward propagation for the no hidden layer network.
for iter in range(1000):
    output0 = X
    output = sigmoid(np.dot(output0,weights) + bias)


    first_term = output - Y
    second_term = output * (1 - output)
    first_two = first_term * second_term
    first_two.shape


    changes = np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
        weights -= lr*changes

    bias_change = 0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias -= bias_change
weights, bias

(array([[5.61401089],
        [5.29693115]]), array([-8.3614485]))

In [74]:
# Optimised version of above code
# Forward propagation for the no hidden layer network.
for iter in range(1000):
    output0 = X
    output = sigmoid(np.dot(output0,weights) + bias)


    first_term = output - Y
    second_term = output * (1 - output)
    first_two = first_term * second_term
    first_two.shape


    changes = np.dot(output0.T, first_two)
    weights -= lr*changes
    bias_change = sum(first_two)
    bias -= bias_change
weights, bias

(array([[5.90621896],
        [5.76342587]]), array([-8.92426721]))

In [75]:
output = sigmoid(np.dot(X,weights) + bias)
output

array([[1.33101267e-04],
       [4.66171417e-02],
       [4.06662182e-02],
       [9.39651764e-01]])